import { flushPromises, mount } from '@vue/test-utils'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import ExecutionOwnerEditor from './ExecutionOwnerEditor.vue'

const api = vi.hoisted(() => ({ listExecutionOwnerOptions: vi.fn(), updateRequirement: vi.fn() }))
vi.mock('@/api/requirement', () => api)
vi.mock('element-plus', () => ({ ElMessage: { success: vi.fn(), warning: vi.fn() } }))
const requirement = { id: 10, version: 3, dev_lead_id: 2, dev_lead: { id: 2, display_name: 'Current owner' }, allowed_actions: ['assign_owner'] }
const stubs = {
  ElButton: { props: ['disabled', 'loading'], template: '<button :disabled="disabled || loading"><slot /></button>' },
  ElDialog: { name: 'ElDialog', props: ['modelValue'], emits: ['update:modelValue'], template: '<div v-if="modelValue"><slot /><slot name="footer" /></div>' },
  ElSelect: { props: ['modelValue'], emits: ['update:modelValue'], template: '<select :value="modelValue" @change="$emit(\'update:modelValue\', $event.target.value)"><slot /></select>' },
  ElOption: { props: ['value', 'label'], template: '<option :value="value">{{ label }}</option>' },
  ElFormItem: { template: '<div><slot /></div>' },
}
const render = value => mount(ExecutionOwnerEditor, { props: { requirement: value ?? requirement }, global: { stubs } })
async function open(wrapper) {
  await wrapper.get('[data-testid="edit-execution-owner"]').trigger('click')
  await flushPromises()
}
beforeEach(() => {
  vi.clearAllMocks()
  api.listExecutionOwnerOptions.mockResolvedValue({ data: { data: [{ id: 2, display_name: 'Current owner' }, { id: 7, display_name: 'New owner' }] } })
  api.updateRequirement.mockResolvedValue({ data: { data: {} } })
})
describe('execution owner editor', () => {
  it('shows current owner without exposing assignment to unauthorized users', async () => {
    const wrapper = render({ ...requirement, allowed_actions: ['edit'] })
    expect(wrapper.text()).toContain('Current owner')
    expect(wrapper.find('[data-testid="edit-execution-owner"]').exists()).toBe(false)
    expect(api.listExecutionOwnerOptions).not.toHaveBeenCalled()
  })
  it('sends a scoped user id with the version captured at dialog open', async () => {
    const wrapper = render()
    await open(wrapper)
    await wrapper.get('select').setValue('7')
    await wrapper.get('[data-testid="save-execution-owner"]').trigger('click')
    await flushPromises()
    expect(api.listExecutionOwnerOptions).toHaveBeenCalledWith(10)
    expect(api.updateRequirement).toHaveBeenCalledWith(10, { dev_lead_id: 7, version: 3 })
    expect(wrapper.emitted('updated')).toHaveLength(1)
  })
  it('retains input on failed save', async () => {
    api.updateRequirement.mockRejectedValueOnce(new Error('save failed'))
    const wrapper = render()
    await open(wrapper)
    await wrapper.get('select').setValue('7')
    await wrapper.get('[data-testid="save-execution-owner"]').trigger('click')
    await flushPromises()
    expect(wrapper.text()).toContain('save failed')
    expect(wrapper.get('select').element.value).toBe('7')
    expect(wrapper.emitted('updated')).toBeUndefined()
  })
  it.each(['STALE_VERSION', undefined])('retains stale selection and requires explicit reload after 409 (%s)', async error_code => {
    api.updateRequirement.mockRejectedValueOnce({ response: { status: 409, data: { error_code, message: 'Changed by another user' } } })
    const wrapper = render()
    await open(wrapper)
    await wrapper.get('select').setValue('7')
    await wrapper.get('[data-testid="save-execution-owner"]').trigger('click')
    await flushPromises()
    expect(wrapper.emitted('stale')).toBeUndefined()
    expect(wrapper.get('select').element.value).toBe('7')
    expect(wrapper.text()).toContain('Changed by another user')
    expect(wrapper.get('[data-testid="save-execution-owner"]').element.disabled).toBe(true)
    await wrapper.get('[data-testid="save-execution-owner"]').trigger('click')
    expect(api.updateRequirement).toHaveBeenCalledTimes(1)
    await wrapper.get('[data-testid="reload-execution-owner"]').trigger('click')
    expect(wrapper.emitted('stale')).toHaveLength(1)
    expect(api.updateRequirement).toHaveBeenCalledTimes(1)
  })
  it.each([undefined, null, '3', 0, -1, 3.5])('rejects invalid revision %s without sending an unlocked mutation', async version => {
    const wrapper = render({ ...requirement, version })
    await open(wrapper)
    await wrapper.get('select').setValue('7')
    await wrapper.get('[data-testid="save-execution-owner"]').trigger('click')
    await flushPromises()
    expect(api.updateRequirement).not.toHaveBeenCalled()
    expect(wrapper.find('[role="alert"]').exists()).toBe(true)
  })
  it('keeps the opened revision when parent data changes before save', async () => {
    const wrapper = render()
    await open(wrapper)
    await wrapper.setProps({ requirement: { ...requirement, version: 4 } })
    await wrapper.get('select').setValue('7')
    await wrapper.get('[data-testid="save-execution-owner"]').trigger('click')
    await flushPromises()
    expect(api.updateRequirement).toHaveBeenCalledWith(10, { dev_lead_id: 7, version: 3 })
  })
  it('blocks a save when assign_owner is revoked while the dialog is open', async () => {
    const wrapper = render()
    await open(wrapper)
    await wrapper.setProps({ requirement: { ...requirement, allowed_actions: [] } })
    await wrapper.get('[data-testid="save-execution-owner"]').trigger('click')
    await flushPromises()
    expect(api.updateRequirement).not.toHaveBeenCalled()
  })
  it('cannot dismiss and reopen a stale dialog to bypass reload', async () => {
    api.updateRequirement.mockRejectedValueOnce({ response: { status: 409, data: { error_code: 'STALE_VERSION', message: 'Conflict' } } })
    const wrapper = render()
    await open(wrapper)
    await wrapper.get('select').setValue('7')
    await wrapper.get('[data-testid="save-execution-owner"]').trigger('click')
    await flushPromises()
    wrapper.findComponent({ name: 'ElDialog' }).vm.$emit('update:modelValue', false)
    await flushPromises()
    await wrapper.setProps({ requirement: { ...requirement, version: 4 } })
    await open(wrapper)
    expect(wrapper.get('select').element.value).toBe('7')
    expect(wrapper.text()).toContain('Conflict')
    expect(wrapper.get('[data-testid="save-execution-owner"]').element.disabled).toBe(true)
    expect(api.listExecutionOwnerOptions).toHaveBeenCalledTimes(1)
    expect(api.updateRequirement).toHaveBeenCalledTimes(1)
  })
  it('retries an options failure without permitting a save against unavailable options', async () => {
    api.listExecutionOwnerOptions.mockRejectedValueOnce(new Error('Directory unavailable'))
    const wrapper = render()
    await open(wrapper)
    expect(wrapper.text()).toContain('Directory unavailable')
    expect(wrapper.get('[data-testid="save-execution-owner"]').element.disabled).toBe(true)
    await wrapper.get('[role="alert"] button').trigger('click')
    await flushPromises()
    expect(api.listExecutionOwnerOptions).toHaveBeenCalledTimes(2)
    await wrapper.get('select').setValue('7')
    await wrapper.get('[data-testid="save-execution-owner"]').trigger('click')
    await flushPromises()
    expect(api.updateRequirement).toHaveBeenCalledTimes(1)
  })
  it('allows deliberate retry after a failed save while retaining the opened revision', async () => {
    api.updateRequirement.mockRejectedValueOnce(new Error('Save unavailable'))
    const wrapper = render()
    await open(wrapper)
    await wrapper.get('select').setValue('7')
    await wrapper.get('[data-testid="save-execution-owner"]').trigger('click')
    await flushPromises()
    expect(wrapper.get('select').element.value).toBe('7')
    await wrapper.get('[data-testid="save-execution-owner"]').trigger('click')
    await flushPromises()
    expect(api.updateRequirement).toHaveBeenNthCalledWith(2, 10, { dev_lead_id: 7, version: 3 })
  })
  it('prevents duplicate submissions until a pending save completes', async () => {
    let finishSave
    api.updateRequirement.mockImplementationOnce(() => new Promise(resolve => { finishSave = resolve }))
    const wrapper = render()
    await open(wrapper)
    const save = wrapper.get('[data-testid="save-execution-owner"]')
    save.element.click()
    save.element.click()
    await flushPromises()
    expect(api.updateRequirement).toHaveBeenCalledTimes(1)
    expect(save.element.disabled).toBe(true)
    finishSave({ data: { data: {} } })
    await flushPromises()
    expect(wrapper.emitted('updated')).toHaveLength(1)
  })
})
