import { flushPromises, mount } from '@vue/test-utils'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import ProjectMembers from './ProjectMembers.vue'

const api = vi.hoisted(() => ({ listProjectMembers: vi.fn(), listProjectMemberOptions: vi.fn(), addProjectMember: vi.fn(), removeProjectMember: vi.fn() }))
const confirm = vi.hoisted(() => vi.fn())
vi.mock('@/api/projectMembership', () => api)
vi.mock('element-plus', () => ({ ElMessage: { success: vi.fn() }, ElMessageBox: { confirm } }))
const response = data => ({ data: { data } })
const project = { id: 12, allowed_actions: ['manage_members'] }
const stubs = {
  ElButton: { props: ['disabled', 'loading'], template: '<button :disabled="disabled || loading"><slot /></button>' },
  ElDialog: { props: ['modelValue'], template: '<div v-if="modelValue"><slot /><slot name="footer" /></div>' },
  ElSelect: { props: ['modelValue'], emits: ['update:modelValue'], template: '<select :value="modelValue" @change="$emit(\'update:modelValue\', $event.target.value)"><slot /></select>' },
  ElOption: { props: ['value', 'label'], template: '<option :value="value">{{ label }}</option>' },
  ElFormItem: { template: '<div><slot /></div>' },
}
const render = p => mount(ProjectMembers, { props: { project: p ?? project }, global: { stubs } })

beforeEach(() => {
  vi.clearAllMocks()
  api.listProjectMembers.mockResolvedValue(response([{ user_id: 1, display_name: 'PM', is_manager: true, is_active: true }]))
  api.listProjectMemberOptions.mockResolvedValue(response([{ id: 7, display_name: 'Tester' }]))
  api.addProjectMember.mockResolvedValue(response([]))
  api.removeProjectMember.mockResolvedValue(response([]))
  confirm.mockResolvedValue('confirm')
})

describe('project members', () => {
  it('loads real members and hides mutations without permission', async () => {
    const wrapper = render({ ...project, allowed_actions: [] })
    await flushPromises()
    expect(api.listProjectMembers).not.toHaveBeenCalled()
    expect(wrapper.find('[data-testid="add-member"]').exists()).toBe(false)
  })
  it('adds a selected real user id then refreshes persisted members', async () => {
    const wrapper = render()
    await flushPromises()
    expect(wrapper.text()).toContain('PM')
    await wrapper.get('[data-testid="add-member"]').trigger('click')
    await flushPromises()
    await wrapper.get('select').setValue('7')
    await wrapper.get('[data-testid="save-member"]').trigger('click')
    await flushPromises()
    expect(api.listProjectMemberOptions).toHaveBeenCalledWith(12)
    expect(api.addProjectMember).toHaveBeenCalledWith(12, { user_id: 7 })
    expect(api.listProjectMembers).toHaveBeenCalledTimes(2)
  })
  it('retains selection on save failure and supports retry', async () => {
    api.addProjectMember.mockRejectedValueOnce({ response: { data: { message: '添加失败' } } })
    const wrapper = render()
    await flushPromises()
    await wrapper.get('[data-testid="add-member"]').trigger('click')
    await flushPromises()
    await wrapper.get('select').setValue('7')
    await wrapper.get('[data-testid="save-member"]').trigger('click')
    await flushPromises()
    expect(wrapper.text()).toContain('添加失败')
    expect(wrapper.get('select').element.value).toBe('7')
    await wrapper.get('[data-testid="save-member"]').trigger('click')
    await flushPromises()
    expect(api.addProjectMember).toHaveBeenCalledTimes(2)
  })
  it('requires confirmation to remove and protects the assigned manager', async () => {
    api.listProjectMembers.mockResolvedValue(response([
      { user_id: 1, display_name: 'PM', is_manager: true }, { user_id: 7, display_name: 'Tester', is_manager: false },
    ]))
    const wrapper = render()
    await flushPromises()
    expect(wrapper.find('[data-testid="remove-member-1"]').exists()).toBe(false)
    await wrapper.get('[data-testid="remove-member-7"]').trigger('click')
    await flushPromises()
    expect(confirm).toHaveBeenCalled()
    expect(api.removeProjectMember).toHaveBeenCalledWith(12, 7)
  })
  it('retries candidate-loading failures without submitting stale options', async () => {
    api.listProjectMemberOptions.mockRejectedValueOnce(new Error('directory unavailable'))
    const wrapper = render()
    await flushPromises()
    await wrapper.get('[data-testid="add-member"]').trigger('click')
    await flushPromises()
    expect(wrapper.text()).toContain('directory unavailable')
    expect(wrapper.get('[data-testid="save-member"]').element.disabled).toBe(true)
    await wrapper.get('[data-testid="retry-member-options"]').trigger('click')
    await flushPromises()
    expect(api.listProjectMemberOptions).toHaveBeenCalledTimes(2)
  })
  it.each(['cancel', 'close'])('locks removal before confirmation and permits retry after %s', async action => {
    api.listProjectMembers.mockResolvedValue(response([{ user_id: 7, display_name: 'Tester', is_manager: false }]))
    let rejectConfirmation
    confirm.mockImplementationOnce(() => new Promise((resolve, reject) => { rejectConfirmation = reject }))
    const wrapper = render()
    await flushPromises()
    const remove = wrapper.get('[data-testid="remove-member-7"]')
    remove.element.click()
    remove.element.click()
    await flushPromises()
    expect(confirm).toHaveBeenCalledTimes(1)
    expect(remove.element.disabled).toBe(true)
    expect(api.removeProjectMember).not.toHaveBeenCalled()
    rejectConfirmation(action)
    await flushPromises()
    expect(remove.element.disabled).toBe(false)
    expect(wrapper.find('[role="alert"]').exists()).toBe(false)
    expect(api.removeProjectMember).not.toHaveBeenCalled()
    await remove.trigger('click')
    await flushPromises()
    expect(confirm).toHaveBeenCalledTimes(2)
    expect(api.removeProjectMember).toHaveBeenCalledTimes(1)
  })
  it('does not duplicate a pending removal mutation', async () => {
    api.listProjectMembers.mockResolvedValue(response([{ user_id: 7, display_name: 'Tester', is_manager: false }]))
    let finishRemoval
    api.removeProjectMember.mockImplementationOnce(() => new Promise(resolve => { finishRemoval = resolve }))
    const wrapper = render()
    await flushPromises()
    await wrapper.get('[data-testid="remove-member-7"]').trigger('click')
    await flushPromises()
    await wrapper.get('[data-testid="remove-member-7"]').trigger('click')
    expect(confirm).toHaveBeenCalledTimes(1)
    expect(api.removeProjectMember).toHaveBeenCalledTimes(1)
    finishRemoval(response([]))
    await flushPromises()
    expect(api.listProjectMembers).toHaveBeenCalledTimes(2)
  })
  it('allows retry after a failed removal without dropping the member', async () => {
    api.listProjectMembers.mockResolvedValue(response([{ user_id: 7, display_name: 'Tester', is_manager: false }]))
    api.removeProjectMember.mockRejectedValueOnce(new Error('Removal unavailable'))
    const wrapper = render()
    await flushPromises()
    await wrapper.get('[data-testid="remove-member-7"]').trigger('click')
    await flushPromises()
    expect(wrapper.text()).toContain('Removal unavailable')
    expect(wrapper.get('[data-testid="remove-member-7"]').element.disabled).toBe(false)
    await wrapper.get('[data-testid="remove-member-7"]').trigger('click')
    await flushPromises()
    expect(confirm).toHaveBeenCalledTimes(2)
    expect(api.removeProjectMember).toHaveBeenCalledTimes(2)
  })
  it('prevents duplicate adds while persisting a selected member', async () => {
    let finishAdd
    api.addProjectMember.mockImplementationOnce(() => new Promise(resolve => { finishAdd = resolve }))
    const wrapper = render()
    await flushPromises()
    await wrapper.get('[data-testid="add-member"]').trigger('click')
    await flushPromises()
    await wrapper.get('select').setValue('7')
    const save = wrapper.get('[data-testid="save-member"]')
    save.element.click()
    save.element.click()
    await flushPromises()
    expect(api.addProjectMember).toHaveBeenCalledTimes(1)
    expect(save.element.disabled).toBe(true)
    finishAdd(response([]))
    await flushPromises()
    expect(api.listProjectMembers).toHaveBeenCalledTimes(2)
  })
  it('shows and retries an initial member-list failure', async () => {
    api.listProjectMembers.mockRejectedValueOnce(new Error('Members unavailable'))
    const wrapper = render()
    await flushPromises()
    expect(wrapper.text()).toContain('Members unavailable')
    await wrapper.get('[role="alert"] button').trigger('click')
    await flushPromises()
    expect(api.listProjectMembers).toHaveBeenCalledTimes(2)
    expect(wrapper.text()).toContain('PM')
    expect(wrapper.find('[role="alert"]').exists()).toBe(false)
  })
})
